### PR TITLE
Fixed data loss occuring when variable contains =

### PR DESCRIPTION
**Pull request by pmioulet**
Split done on the var/set tags using the = char was causing data loss if assigned value contains an equal

### CODE REVIEW

**Comment by marceloverdijk** [comment]
Thx @pmioulet! I will run it against RiveScript test suite and will try to make a bugfix release asap.

**Comment by marceloverdijk** [comment]
Hmm, `com.rivescript.ObjectIT` is failing now. I will need to look into this further.

**Comment by pmioulet** [comment]
-               assertReply("Hello", "Hello world!");
+               assertReply("Hello", "    Hello world!");


Due to the trim not being called on the object macro for the python support.

I had not planned on having this commit in the PR, it's my 1st PR on github
so i might have missed something :(



2018-03-30 8:56 GMT+02:00 Marcel Overdijk <notifications@github.com>:

**Comment by marceloverdijk** [comment]
I reversed the trim commit for now.
If you have text object macro like:

```
> object hello text
    Hello world!
< object
```

then the line should not be trimmed.
Maybe good to focus on this in the Python PR. Just make sure to create a new branch for the Python support.

**Pull request merged**
